# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directories:
      - "**/*" # https://github.com/dependabot/dependabot-core/issues/10525
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "daily"
