name: Publish the mod

on:
  release:
    types: [published]


jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
{% if cookiecutter.includeDataGeneration == "yes" %}
      - name: Generate resources with Gradle
        run: ./gradlew runDatagen
        env:
          DISABLE_PROPERTIES_UPDATE: true
{% endif %}
      - name: Build with Gradle
        run: ./gradlew build
        env:
          DISABLE_PROPERTIES_UPDATE: true
{% if cookiecutter.isLibrary == "yes" %}
      - name: Publish to Maven
        run: ./gradlew publishMavenPublicationToOffsetMods538Repository
        env:
          DISABLE_PROPERTIES_UPDATE: true
          MAVEN_USERNAME: {{ '${{ secrets.MAVEN_USERNAME }}' }}
          MAVEN_PASSWORD: {{ '${{ secrets.MAVEN_PASSWORD }}' }}
{% endif %}
      - name: Upload to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar

      - name: Upload to Modrinth
        run: ./gradlew modrinth
        env:
          MODRINTH_TOKEN: {{ '${{ secrets.MODRINTH_TOKEN }}' }}
          VERSION_NAME: {{ '${{ github.event.release.name }}' }}
          VERSION_IS_PRERELEASE: {{ '${{ github.event.release.prerelease }}' }}
          VERSION_CHANGELOG: {{ '${{ github.event.release.body }}' }}